version: '3.8'
services:
  offers_api:
    image: jacobouribe/offers-api
    container_name: offers_api
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000